name: Tukang Commit

on:
  push:
    branches:
      - master
      
  schedule:
    - cron: "0,30 * * * *"

jobs:
  auto-commit:
    runs-on: ubuntu-26.04
    steps:
      - uses: actions/checkout@v4      
        with:
          ref: ${{ github.head_ref }}
          persist-credentials: false
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Run Bot Task
        run: |
          chmod +x ./task.sh
          ./task.sh
          
      - name: GitHub Push
        uses: ad-m/github-push-action@master
        with:
          force: true
          directory: "."
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
